[package]
name = "limpieza_datos"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
chrono = "0.4"
csv = "1.1"
regex = "1.10.4"
rusqlite = "0.31.0"
lazy_static = "1.4.0"
