[package]
name = "load_reviews"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26"
csv = "1.1"
chrono = "0.4"
lazy_static = "1.4.0"
regex = "1.10.4"